---
title: "Crags We've Climbed"
author: "Joe McGirr"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: no
    theme: paper
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_notebook:
    toc: yes
    toc_depth: 5
  pdf_document:
    toc: yes
    toc_depth: '5'
editor_options:
  chunk_output_type: console
---

```{r}
library(googlesheets4)
library(tidyverse)
#gs4_auth_configure(api_key = "AIzaSyD2r8gf36g15AN9qmDrK8pvyYjNxpgJdqA")
googlesheets4::gs4_deauth()
sites <- read_sheet("https://docs.google.com/spreadsheets/d/1mQcFZHitt_vI2jwdFT7HYhvsNHynVpNDf-Mt_esuFNE/edit?usp=sharing") %>% as.data.frame()
sites <- separate(sites, latitude_longitude, c("lat", "lng"), ", ", remove = TRUE) %>% mutate(lat = as.numeric(lat),lng = as.numeric(lng))

```

```{css, echo=FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
```

# Maps

```{r, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 3}

library(tidyverse)
#library(ggpubr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
#library(ggspatial)
#library(pophelper)
#library(rgeos)


# Wong, B. Points of view: Color blindness. Nat Methods (2011).
bla <- '#000000'
blu <- '#0072b2'
grb <- '#56b4e9'
lir <- '#cc79a7'
gre <- '#009e73'
red <- '#d55e00'
org <- '#e69f00'
yel <- '#f0e442'
gry <- '#BBBBBB'



theme_set(theme_bw())
world <- ne_countries(scale = "medium", returnclass = "sf")

ggplot(data = world) +
  geom_sf() +
  geom_point(data = sites, aes(x = longitude, y = latitude, fill = state), size = 4, 
             shape = 21) +
  #scale_fill_manual(name = "Collection Years",values=c(red,blu,gre,lir,org,grb))+
  #coord_sf(xlim = c(-127, -65), ylim = c(24, 52), expand = FALSE)+
	coord_sf(lims_method = "geometry_bbox")+
  xlab("") + ylab("")
  #theme(legend.position = c(0.23, 0.31))
  #scale_y_continuous(position='right')

```


```{r, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 3}
library(leaflet)
library(shiny)
library(rsconnect)

# https://towardsdatascience.com/making-interactive-maps-in-r-with-less-than-15-lines-of-code-bfd81f587e12

#rsconnect::setAccountInfo(name='joemcgirr',
#			  token='B91EFB89BC89156E081865ADD302254F',
#			  secret='')

ui <- fluidPage(
  leafletOutput("mymap"),
  p(),
  actionButton("recalc", "New points")
)

sites %>% 
leaflet() %>%
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
addLayersControl(baseGroups = c("Toner Lite", "World Imagery")) %>%
addMarkers(label = sites$crag)




server <- function(input, output, session) {

  points <- eventReactive(input$recalc, {
    cbind(rnorm(40) * 2 + 13, rnorm(40) + 48)
  }, ignoreNULL = FALSE)

  output$mymap <- renderLeaflet({
    sites %>% 
leaflet() %>%
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
addLayersControl(baseGroups = c("Toner Lite", "World Imagery")) %>%
addMarkers(label = sites$crag)
  })
}

shinyApp(ui, server)

#

```
